name: GitHub Metrics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: harishmuh
          template: classic
          base: header, activity, community, repositories
          config_timezone: Asia/Jakarta
          output_action: commit
          output_file: github-metrics.svg
